[package]
name = "dgame"
version = "0.1.0"
authors = ["aljazerzen <aljaz@calms.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "^0.34"
gamemath = "^0.4"
rand = "^0.7.3"